{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ritsuko-bot.fullname" . }}
  labels:
    {{- include "ritsuko-bot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.githubMatchboxToken }}
  github-matchbox-token: {{ .Values.secrets.githubMatchboxToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.zulipEmail }}
  zulip-email: {{ .Values.secrets.zulipEmail | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.zulipApiKey }}
  zulip-api-key: {{ .Values.secrets.zulipApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.zulipSite }}
  zulip-site: {{ .Values.secrets.zulipSite | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.nautobotToken }}
  nautobot-token: {{ .Values.secrets.nautobotToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.nautobotUrl }}
  nautobot-url: {{ .Values.secrets.nautobotUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.authorizedUsers }}
  authorized-users: {{ .Values.secrets.authorizedUsers | b64enc | quote }}
  {{- end }}
{{- end }}
